name: Changelog Generator

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  check-commit-message:
    name: Changelog Generator
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate and email notes
        uses: Chathuru/jira-github-changelog@0.0.1
        id: changelog
        with:
          head: 0.4 # origin/main
          base: 0.3 # origin/dev
          jira-code: '(RP|RO)'
          jira-host: org.atlassian.net
          jira-username: email@gmail.com
          jira-password: password
          pdf: false
          unshallow: false

      - name: Get the changelog message
        run: |
          export SUMMARY=$(echo '${{ steps.changelog.outputs.markdown }}' | jq '.markdown')
          printf "$SUMMARY"
          printf "$SUMMARY" > CHANGELOG.md
          printf "$SUMMARY" >> $GITHUB_STEP_SUMMARY

      - name: Print
        run: cat CHANGELOG.md
