name: Go Test

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: aws-ec2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 1.21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'
      - run: mvn clean install
